# Generated by Django 3.0.5 on 2021-07-06 15:18

from django.db import migrations
from django.db import connection, IntegrityError
from psycopg2 import errors


class Migration(migrations.Migration):

    dependencies = [
      ('unit_logs', '0013_auto_20210710_1604'),
    ]

    operations = [
      migrations.RunSQL("insert into unit_logs_status (category, description) VALUES('Failure', 'broken GSM antenna');"),
    ]
